package lib;

/**
 * This class is automatically generated by ncg. DO NOT EDIT THIS FILE. This
 * class includes values of some nesC constants from Oscilloscope.h.
 */
public class Constants {

    public static final byte TEMP = 0;
    public static final byte PHOTO = 1;
    public static final short DEFAULT_INTERVAL = 50;
    public static final byte NREADINGS = 10;
    public static final byte POLL = 0;
    public static final byte READINGANSWER = 4;
    public static final byte READINGREQUEST = 3;
    public static final byte ACK = 1;
    public static final byte PIN_S = 4;
    public static final byte PHOTO_S = 2;
    public static final byte TEMP_S = 1;
    public static final byte SWITCHPOLL = 5;
    public static final byte SWITCHCHANGE = 6;
    public static final byte SWITCHANSWER = 7;
}
